//Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
//By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
//find the sum of the even-valued terms.
var sumEvenFibs = function (maxValue) {
	var fib = [1,2];
	while ((fib[(fib.length-2)]+fib[(fib.length-1)])<=maxValue) {
    	fib.push((fib[(fib.length-2)]+fib[(fib.length-1)]));
	}
	var evenFib = [];
	for (var i=0; i<fib.length; i++) {
    	if (fib[i]%2===0) {
        	evenFib.push(fib[i]);
    	}
	}
	total=0;
	for (var a=0; a<evenFib.length; a++) {
    	total+=evenFib[a];
	}
	return total;
}

console.log(sumEvenFibs(4000000));